package indi.graduate.assistant.model;

import java.util.Date;


public class IntervieweeBean {
    /**
     * 序号
     */
    private Integer intervieweeId;

    /**
     * 姓名
     */
    private String intervieweeName;

    /**
     *性别
     */
    private Integer intervieweeSex;
    private String intervieweeSexStr;
    /**
     * 联系方式
     */
    private String intervieweePhone;

    /**
     * 面试状态
     */
    private Integer intervieweeStatus;
    /**
     * 面试次数
     */
    private Integer intervieweeNum;

    /**
     * 最后一次面试时间
     */
    private Date intervieweeLastTime;
    /**
     *毕业学校
     */
    private String intervieweeSchool;

    /**
     *毕业时间
     */
    private Date intervieweeGraduationTime;
    private String graduationTime;
    /**
     *应聘岗位
     */
    private String intervieweePost;

    /**
     * 应聘项目
     */
    private String intervieweeProject;

    /**
     * 专业特长
     */
    private String intervieweePecialties;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.interviewee_id
     *
     * @return the value of interviewee.interviewee_id
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public Integer getIntervieweeId() {
        return intervieweeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.interviewee_id
     *
     * @param intervieweeId the value for interviewee.interviewee_id
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweeId(Integer intervieweeId) {
        this.intervieweeId = intervieweeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.interviewee_name
     *
     * @return the value of interviewee.interviewee_name
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public String getIntervieweeName() {
        return intervieweeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.interviewee_name
     *
     * @param intervieweeName the value for interviewee.interviewee_name
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweeName(String intervieweeName) {
        this.intervieweeName = intervieweeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.interviewee_sex
     *
     * @return the value of interviewee.interviewee_sex
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public Integer getIntervieweeSex() {
        return intervieweeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.interviewee_sex
     *
     * @param intervieweeSex the value for interviewee.interviewee_sex
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweeSex(Integer intervieweeSex) {
        this.intervieweeSex = intervieweeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.interviewee_phone
     *
     * @return the value of interviewee.interviewee_phone
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public String getIntervieweePhone() {
        return intervieweePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.interviewee_phone
     *
     * @param intervieweePhone the value for interviewee.interviewee_phone
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweePhone(String intervieweePhone) {
        this.intervieweePhone = intervieweePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.interviewee_status
     *
     * @return the value of interviewee.interviewee_status
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public Integer getIntervieweeStatus() {
        return intervieweeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.interviewee_status
     *
     * @param intervieweeStatus the value for interviewee.interviewee_status
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweeStatus(Integer intervieweeStatus) {
        this.intervieweeStatus = intervieweeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.interviewee_school
     *
     * @return the value of interviewee.interviewee_school
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public String getIntervieweeSchool() {
        return intervieweeSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.interviewee_school
     *
     * @param intervieweeSchool the value for interviewee.interviewee_school
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweeSchool(String intervieweeSchool) {
        this.intervieweeSchool = intervieweeSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.Interviewee_graduation_time
     *
     * @return the value of interviewee.Interviewee_graduation_time
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public Date getIntervieweeGraduationTime() {
        return intervieweeGraduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.Interviewee_graduation_time
     *
     * @param intervieweeGraduationTime the value for interviewee.Interviewee_graduation_time
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweeGraduationTime(Date intervieweeGraduationTime) {
        this.intervieweeGraduationTime = intervieweeGraduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.Interviewee_post
     *
     * @return the value of interviewee.Interviewee_post
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public String getIntervieweePost() {
        return intervieweePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.Interviewee_post
     *
     * @param intervieweePost the value for interviewee.Interviewee_post
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweePost(String intervieweePost) {
        this.intervieweePost = intervieweePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.Interviewee_project
     *
     * @return the value of interviewee.Interviewee_project
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public String getIntervieweeProject() {
        return intervieweeProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.Interviewee_project
     *
     * @param intervieweeProject the value for interviewee.Interviewee_project
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweeProject(String intervieweeProject) {
        this.intervieweeProject = intervieweeProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interviewee.Interviewee_pecialties
     *
     * @return the value of interviewee.Interviewee_pecialties
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public String getIntervieweePecialties() {
        return intervieweePecialties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interviewee.Interviewee_pecialties
     *
     * @param intervieweePecialties the value for interviewee.Interviewee_pecialties
     *
     * @mbggenerated Mon Aug 29 20:31:56 CST 2016
     */
    public void setIntervieweePecialties(String intervieweePecialties) {
        this.intervieweePecialties = intervieweePecialties;
    }

	public Integer getIntervieweeNum() {
		return intervieweeNum;
	}

	public void setIntervieweeNum(Integer intervieweeNum) {
		this.intervieweeNum = intervieweeNum;
	}

	public Date getIntervieweeLastTime() {
		return intervieweeLastTime;
	}

	public void setIntervieweeLastTime(Date intervieweeLastTime) {
		this.intervieweeLastTime = intervieweeLastTime;
	}

	public String getGraduationTime() {
		return graduationTime;
	}

	public void setGraduationTime(String graduationTime) {
		this.graduationTime = graduationTime;
	}

	public String getIntervieweeSexStr() {
		return intervieweeSexStr;
	}

	public void setIntervieweeSexStr(String intervieweeSexStr) {
		this.intervieweeSexStr = intervieweeSexStr;
	}
    
	
}