package indi.graduate.assistant.model;

public class QuestionBeanWithBLOBs extends QuestionBean {
    /**
     * 题目
     */
    private String questionTopic;
    /**
     * 完整题目
     */
    private String questionQuestion;
    /**
     *答案
     */
    private String questionAnswers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_topic
     *
     * @return the value of question.question_topic
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public String getQuestionTopic() {
        return questionTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_topic
     *
     * @param questionTopic the value for question.question_topic
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public void setQuestionTopic(String questionTopic) {
        this.questionTopic = questionTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_answers
     *
     * @return the value of question.question_answers
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public String getQuestionAnswers() {
        return questionAnswers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_answers
     *
     * @param questionAnswers the value for question.question_answers
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public void setQuestionAnswers(String questionAnswers) {
        this.questionAnswers = questionAnswers;
    }

	public String getQuestionQuestion() {
		return questionQuestion;
	}

	public void setQuestionQuestion(String questionQuestion) {
		this.questionQuestion = questionQuestion;
	}
    
}