package indi.graduate.assistant.model;

public class QuestionBean {
    /**
     * 序号
     */
    private Integer questionId;

    /**
     *题目类型
     */
    private Integer questionType;

    /**
     * 难易程度
     */
    private Integer questionDifficulty;

    /**
     * 使用场景 111代表现场，电话，视频权限',
     */
    private Integer questionFaceWay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_id
     *
     * @return the value of question.question_id
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_id
     *
     * @param questionId the value for question.question_id
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_type
     *
     * @return the value of question.question_type
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_type
     *
     * @param questionType the value for question.question_type
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_difficulty
     *
     * @return the value of question.question_difficulty
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public Integer getQuestionDifficulty() {
        return questionDifficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_difficulty
     *
     * @param questionDifficulty the value for question.question_difficulty
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public void setQuestionDifficulty(Integer questionDifficulty) {
        this.questionDifficulty = questionDifficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_face_way
     *
     * @return the value of question.question_face_way
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public Integer getQuestionFaceWay() {
        return questionFaceWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_face_way
     *
     * @param questionFaceWay the value for question.question_face_way
     *
     * @mbggenerated Mon Aug 29 20:34:08 CST 2016
     */
    public void setQuestionFaceWay(Integer questionFaceWay) {
        this.questionFaceWay = questionFaceWay;
    }
}